<script lang="ts">
  import Icon from "$lib/components/ui/Icon/index.js";
  import { createEventDispatcher } from 'svelte';

  const dispatch = createEventDispatcher();

  export let show = false;
  let activeView = "Combined View";

  const close = () => dispatch('close');
</script>

{#if show}
  <div class="fixed inset-0 z-[60] flex items-center justify-center bg-black/50 backdrop-blur-sm">
    <div class="bg-white rounded-xl shadow-2xl w-full max-w-4xl overflow-hidden max-h-[90vh] flex flex-col">
      <div class="flex items-center justify-between p-6 border-b">
        <div>
          <h2 class="text-xl font-bold text-gray-900">Report Preview</h2>
          <p class="text-xs text-gray-500">Review the report before sending or exporting.</p>
        </div>
        <button on:click={close} class="text-gray-400 hover:text-gray-600">
          <Icon iconName="icon/x-circle" size={20} />
        </button>
      </div>

      <div class="grid grid-cols-4 divide-x border-b bg-gray-50/30">
        <div class="p-4">
          <p class="text-[10px] text-gray-500 uppercase font-bold mb-1">Report Type</p>
          <span class="px-2 py-1 bg-info/10 text-info text-[10px] rounded-full font-bold">Sales Report</span>
        </div>
        <div class="p-4">
          <p class="text-[10px] text-gray-500 uppercase font-bold mb-1">Date Range</p>
          <p class="text-sm font-bold">Oct 1 - Oct 31, 2023</p>
        </div>
        <div class="p-4">
          <p class="text-[10px] text-gray-500 uppercase font-bold mb-1">Generated At</p>
          <p class="text-sm font-bold">Nov 1, 10:00 AM</p>
        </div>
        <div class="p-4">
          <p class="text-[10px] text-gray-500 uppercase font-bold mb-1">Generated By</p>
          <div class="flex items-center gap-2">
            <Icon iconName="icon/package" size={14} class="text-gray-400"/>
            <p class="text-sm font-bold">Admin User</p>
          </div>
        </div>
      </div>

      <div class="flex-1 overflow-y-auto p-6 space-y-6">
        <div class="flex items-center justify-between border-b">
          <div class="flex gap-6">
            {#each ["Combined View", "Table Only"] as tab}
              <button 
                class="pb-3 text-sm font-bold transition-all {activeView === tab ? 'text-info border-b-2 border-info' : 'text-gray-400'}"
                on:click={() => activeView = tab}>
                <div class="flex items-center gap-2">
                   <Icon iconName={tab === 'Table Only' ? 'icon/file-text' : 'icon/package'} size={14} />
                   {tab}
                </div>
              </button>
            {/each}
          </div>
          <span class="text-[10px] bg-gray-100 text-gray-500 px-2 py-1 rounded">Read-only Preview</span>
        </div>

        <div class="border rounded-xl p-6 space-y-8">
          <div class="space-y-3">
            <p class="text-[10px] font-bold text-gray-400 uppercase">Text Summary (SMS)</p>
            <div class="bg-gray-50 p-4 rounded-lg flex gap-4 max-w-lg border border-dashed">
              <div class="w-10 h-10 bg-info/10 rounded-lg flex items-center justify-center text-info">
                <Icon iconName="icon/package" size={20} />
              </div>
              <div class="flex-1">
                 <p class="text-xs font-bold text-gray-900 mb-1">BamanStock System <span class="font-normal text-gray-400 ml-2 italic">Now</span></p>
                 <div class="bg-white p-3 rounded-lg border shadow-sm text-xs leading-relaxed text-gray-700">
                    BamanStock Daily Summary: Total Sales: $1,200 | Items Sold: 45 | Credits: $200. Log in to view full details.
                 </div>
              </div>
            </div>
          </div>

          <div class="space-y-3">
            <p class="text-[10px] font-bold text-gray-400 uppercase">Table Detail View</p>
            <table class="w-full text-xs">
              <thead class="uppercase bg-gray-50 border-y">
                <tr>
                  <th class="text-left px-4 py-3 font-bold uppercase text-gray-500">Product</th>
                  <th class="text-left px-4 py-3 font-bold uppercase text-gray-500">Customer</th>
                  <th class="text-right px-4 py-3 font-bold uppercase text-gray-500">Total Amount</th>
                  <th class="text-right px-4 py-3 font-bold uppercase text-gray-500">Date</th>
                </tr>
              </thead>
              <tbody class="divide-y">
                <tr>
                  <td class="px-4 py-4 font-bold">Lenovo IdeaPad 3</td>
                  <td class="px-4 py-4 text-gray-500">Stan Gaunter</td>
                  <td class="px-4 py-4 text-right font-bold">$500.00</td>
                  <td class="px-4 py-4 text-right text-gray-400">Oct 31</td>
                </tr>
                <tr>
                  <td class="px-4 py-4 font-bold">Lenovo IdeaPad 3</td>
                  <td class="px-4 py-4 text-gray-500">Stan Gaunter</td>
                  <td class="px-4 py-4 text-right font-bold">$500.00</td>
                  <td class="px-4 py-4 text-right text-gray-400">Oct 30</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <div class="p-6 border-t flex justify-end gap-3 bg-gray-50/50">
        <button on:click={close} class="px-6 py-2.5 border rounded-lg text-sm font-medium hover:bg-white transition-colors">Cancel</button>
        <button class="px-6 py-2.5 border border-info text-info rounded-lg text-sm font-medium hover:bg-info/5 transition-colors">Export Report</button>
        <button class="px-6 py-2.5 bg-info text-white rounded-lg text-sm font-medium hover:bg-info/90 shadow-lg shadow-info/20">Send Report</button>
      </div>
    </div>
  </div>
{/if}