query getLandingMerchants(
  $limit: Int
  $offset: Int
  $filter: merchant_bool_exp
  $order: [merchant_order_by!]!
  $ordersFilter: orders_bool_exp = {}
) {
  merchant(limit: $limit, offset: $offset, where: $filter, order_by: $order) {
    id
    first_name
    last_name
    address
    phone_number
    branch: branchByBranch {
      id
      name
      address
      company
      created_at
    }
    total_orders: orders_aggregate(where: $ordersFilter) {
      aggregate {
        count
      }
    }
    sales: orders_aggregate(where: $ordersFilter) {
      aggregate {
        sum {
          total_amount
        }
      }
    }
    total_outstanding: orders_aggregate(where: $ordersFilter) {
      aggregate {
        sum {
          outstanding_amount
        }
      }
    }
  }
  total: merchant_aggregate(where: $filter) {
    aggregate {
      count
    }
  }
  total_merchants: merchant_aggregate {
    aggregate {
      count
    }
  }
  active_merchants: merchant_aggregate(where: { orders: $ordersFilter }) {
    aggregate {
      count
    }
  }
  merchants_location: branches_aggregate(
    where: { merchants: { id: { _is_null: false } } }
  ) {
    aggregate {
      count
    }
  }
}
