query getLandingMerchants(
  $limit: Int
  $offset: Int
  $filter: merchant_bool_exp
  $order: [merchant_order_by!]!
) {
  merchant(limit: $limit, offset: $offset, where: $filter, order_by: $order) {
    id
    first_name
    last_name
    address
    phone_number
    total_investors
    branch: branchByBranch {
      id
      name
      address
      company
      created_at
    }
    orders_aggregate {
      aggregate {
        count
      }
    }
  }
  total_merchants: merchant_aggregate(where: $filter) {
    aggregate {
      count
    }
  }
}
