query getStockMovementStats($filter: stock_movements_bool_exp!) {
  total_stocks_in: stock_movements_aggregate(
    where: {
      _and: [
        {
          _or: [
            { movement_type: { _eq: "PURCHASE" } }
            { movement_type: { _eq: "TRANSFER_IN" } }
          ]
        }
        $filter
      ]
    }
  ) {
    aggregate {
      sum {
        quantity_delta
      }
    }
  }
  total_stocks_out: stock_movements_aggregate(
    where: {
      _and: [
        {
          _or: [
            { movement_type: { _eq: "TRANSFER_OUT" } }
            { movement_type: { _eq: "SALE" } }
          ]
        }
        $filter
      ]
    }
  ) {
    aggregate {
      sum {
        quantity_delta
      }
    }
  }
  number_of_transfers: stock_movements_aggregate(where: $filter) {
    aggregate {
      count
    }
  }
}