<script lang="ts">
  import { Button } from "$lib/components/ui/button/index.js";
  import Icon from "$lib/components/ui/Icon/index.js";
  import { Input } from "$lib/components/ui/input/index.js";
  import SearchSelect from "$lib/components/investor/search-select/SearchSelect.svelte";
  import { getAuthClient } from "$graphql/client.ts";
  import { authStore } from "$lib/stores/auth.svelte.js";
  import INSERT_PRODUCT from "$graphql/mutation/product/insert.gql";
  import UPDATE_PRODUCT from "$graphql/mutation/product/update.gql";
  import PRODUCT_DETAIL_QUERY from "$graphql/queries/product/detail/product_by_id.gql";
  import PRODUCT_CATEGORY_QUERY from "$graphql/queries/selector/product_category.gql";
  import COMPANY_QUERY from "$graphql/queries/selector/company.gql";
  import MERCHANT_QUERY from "$graphql/queries/selector/merchant.gql";
  import {
    usesAutoGeneratedProductName,
    buildCatalogProductName,
  } from "$lib/inventory/product-labels";

  interface CreateProductModalProps {
    isOpen?: boolean;
    productId?: string;
    onClose?: () => void;
    onSuccess?: () => void;
  }

  let {
    isOpen = $bindable(false),
    productId = "",
    onClose,
    onSuccess,
  }: CreateProductModalProps = $props();

  const isEditMode = $derived(Boolean(productId));

  const UNIT_OPTIONS = [
    "Pieces", "Set", "kg", "g", "Ltr", "mL", "Box", "Pair",
    "Pack", "Roll", "Dozen", "m", "m2", "Tonne",
  ];

  let productName = $state("");
  let productTypeId = $state("");
  let productTypeName = $state("");
  let defaultUnit = $state("");
  let companyId = $state("");
  let merchantId = $state("");
  let barcode = $state("");
  let qrCode = $state("");
  let threshold = $state("");
  let modelNo = $state("");
  let country = $state("");
  let thickness = $state("");
  let color = $state("");
  let figure = $state("");
  let factor = $state("");
  let productTypes = $state<Array<{ id: string; name: string }>>([]);
  let loading = $state(false);
  let error = $state<string | null>(null);
  let detailLoading = $state(false);
  let isActive = $state(true);

  const selectedTypeKey = $derived(productTypeName.trim().toLowerCase());
  const autoName = $derived(usesAutoGeneratedProductName(selectedTypeKey));

  const attributes = $derived.by(() => {
    const attrs: Record<string, string> = {};
    if (selectedTypeKey === "brake_lining" || selectedTypeKey === "brake_pad" || selectedTypeKey === "break_pad") {
      if (modelNo.trim()) attrs.model_number = modelNo.trim();
      if (country.trim()) attrs.country = country.trim();
    } else if (selectedTypeKey === "glass") {
      if (thickness.trim()) attrs.thickness = thickness.trim();
      if (color.trim()) attrs.color = color.trim();
      if (figure.trim()) attrs.figure = figure.trim();
      if (factor.trim()) attrs.factor = factor.trim();
    }
    return attrs;
  });

  const generatedName = $derived(
    autoName ? buildCatalogProductName(selectedTypeKey, attributes) : ""
  );

  const displayName = $derived(autoName ? generatedName : productName);

  $effect(() => {
    if (!isOpen) return;
    const client = getAuthClient("investor");
    client
      .query<{ product_types: Array<{ id: string; name: string }> }>({
        query: PRODUCT_CATEGORY_QUERY,
        variables: { limit: 100, offset: 0, filter: {} },
      })
      .then((r) => {
        productTypes = r.data?.product_types ?? [];
      })
      .catch(() => {});
  });

  $effect(() => {
    if (!isOpen) return;
    if (productId) {
      loadProductDetail(productId);
    } else {
      resetForm();
    }
  });

  async function loadProductDetail(id: string) {
    detailLoading = true;
    error = null;
    try {
      const client = getAuthClient("investor");
      const result = await client.query({
        query: PRODUCT_DETAIL_QUERY,
        variables: { id },
      });
      const p = (result.data as any)?.products_by_pk ?? null;
      if (!p) return;
      productName = p.name ?? "";
      productTypeId = p.product_type?.id ?? "";
      productTypeName = p.product_type?.name ?? "";
      defaultUnit = p.default_unit ?? "";
      companyId = p.company_id ?? "";
      merchantId = p.created_by ?? "";
      barcode = p.barcode ?? "";
      qrCode = p.qr_code ?? "";
      threshold = p.treshold_quantity != null ? String(p.treshold_quantity) : "";
      isActive = p.is_active ?? true;
      const attrs = p.attributes ?? {};
      modelNo = attrs.model_number != null ? String(attrs.model_number) : "";
      country = attrs.country != null ? String(attrs.country) : "";
      thickness = attrs.thickness != null ? String(attrs.thickness) : "";
      color = attrs.color != null ? String(attrs.color) : "";
      figure = attrs.figure != null ? String(attrs.figure) : "";
      factor = attrs.factor != null ? String(attrs.factor) : "";
    } catch (err: any) {
      error = err.message ?? "Failed to load product details";
    } finally {
      detailLoading = false;
    }
  }

  function resetForm() {
    productName = "";
    productTypeId = "";
    productTypeName = "";
    defaultUnit = "";
    companyId = "";
    merchantId = "";
    barcode = "";
    qrCode = "";
    threshold = "";
    modelNo = "";
    country = "";
    thickness = "";
    color = "";
    figure = "";
    factor = "";
    isActive = true;
    detailLoading = false;
    error = null;
  }

  function handleClose() {
    isOpen = false;
    resetForm();
    onClose?.();
  }

  function handleBackdropClick(e: MouseEvent) {
    if (e.target === e.currentTarget && !loading) {
      handleClose();
    }
  }

  function handleEscape(e: KeyboardEvent) {
    if (e.key === "Escape" && !loading) {
      handleClose();
    }
  }

  function handleProductTypeSelect(e: Event) {
    const select = e.currentTarget as HTMLSelectElement;
    const selected = productTypes.find((t) => t.id === select.value);
    productTypeId = selected?.id ?? "";
    productTypeName = selected?.name ?? "";
  }

  async function handleSubmit() {
    if (!companyId) {
      error = "Company is required";
      return;
    }
    if (!merchantId) {
      error = "Merchant is required";
      return;
    }
    if (!productTypeId) {
      error = "Product type is required";
      return;
    }
    if (!defaultUnit) {
      error = "Default unit is required";
      return;
    }
    if (!displayName.trim() || (autoName && displayName === "Stock")) {
      error = autoName
        ? "Fill in the attributes above to build the product name"
        : "Product name is required";
      return;
    }

    const investorId = authStore.user?.investorId ?? "";

    const object: Record<string, unknown> = {
      name: displayName.trim(),
      company_id: companyId,
      product_type_id: productTypeId,
      default_unit: defaultUnit,
      updated_by: merchantId,
    };

    if (Object.keys(attributes).length > 0) {
      object.attributes = attributes;
    }
    function toTrimmed(v: unknown): string {
      return v == null ? "" : String(v).trim();
    }

    const barcodeVal = toTrimmed(barcode);
    const qrCodeVal = toTrimmed(qrCode);
    const thresholdVal = toTrimmed(threshold);
    const factorVal = toTrimmed(factor);

    if (barcodeVal) object.barcode = barcodeVal;
    if (qrCodeVal) object.qr_code = qrCodeVal;
    if (thresholdVal) object.treshold_quantity = Number(thresholdVal);
    if (selectedTypeKey === "glass" && factorVal) {
      object.factor = Number(factorVal);
    }

    if (isEditMode) {
      object.is_active = isActive;
    } else {
      if (!investorId) {
        error = "Unable to determine the current investor";
        return;
      }
      object.investors = [investorId];
      object.created_by = merchantId;
    }

    loading = true;
    error = null;

    try {
      const client = getAuthClient("investor");
      if (isEditMode) {
        await client.mutate({
          mutation: UPDATE_PRODUCT,
          variables: { id: productId, object },
        });
      } else {
        await client.mutate({
          mutation: INSERT_PRODUCT,
          variables: { object },
        });
      }
      onSuccess?.();
      handleClose();
    } catch (err: any) {
      error = err.message ?? "An unexpected error occurred";
    } finally {
      loading = false;
    }
  }
</script>

{#if isOpen}
  <div
    class="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-4"
    onclick={handleBackdropClick}
    onkeydown={handleEscape}
    role="dialog"
    aria-modal="true"
    aria-labelledby="product-modal-title"
    tabindex="-1"
  >
    <div
      class="bg-card rounded-lg shadow-xl w-full max-w-2xl max-h-[90vh] overflow-y-auto"
      onclick={(e) => e.stopPropagation()}
      role="document"
    >
      <div class="flex items-center justify-between p-6 border-b border-border">
        <h2 id="product-modal-title" class="text-xl font-bold text-foreground">
          {isEditMode ? "Edit Product" : "Create New Product"}
        </h2>
        <button
          type="button"
          class="p-1 rounded-md hover:bg-muted transition-colors disabled:opacity-30"
          onclick={handleClose}
          disabled={loading}
          aria-label="Close modal"
        >
          <Icon iconName="icon/x" size={20} class="text-foreground" />
        </button>
      </div>

      <div class="p-6 space-y-6">
        {#if error}
          <div class="p-3 rounded-md bg-destructive/10 border border-destructive/20 flex items-start gap-2">
            <Icon iconName="icon/alert-circle" size={16} class="text-destructive shrink-0 mt-0.5" />
            <p class="text-sm text-destructive">{error}</p>
          </div>
        {/if}

        {#if isEditMode && detailLoading}
          <div class="space-y-4">
            {#each [1,2,3,4,5,6] as _}
              <div class="h-10 bg-muted/60 rounded animate-pulse"></div>
            {/each}
          </div>
        {:else}
        <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div class="space-y-2 md:col-span-2">
            <label for="company" class="text-sm font-medium text-foreground">
              Company <span class="text-destructive">*</span>
            </label>
            <SearchSelect
              query={COMPANY_QUERY}
              dataKey="companies"
              filterBuilder={(s) => ({ name: { _ilike: `%${s}%` } })}
              displayLabel={(item) => item.name}
              placeholder="Search and select company"
              initialValue={companyId}
              onSelect={(item) => (companyId = item?.id ?? "")}
            />
          </div>

          <div class="space-y-2 md:col-span-2">
            <label for="merchant" class="text-sm font-medium text-foreground">
              Merchant <span class="text-destructive">*</span>
            </label>
            <SearchSelect
              query={MERCHANT_QUERY}
              dataKey="merchant"
              filterBuilder={(s) => ({
                _or: [
                  { first_name: { _ilike: `%${s}%` } },
                  { last_name: { _ilike: `%${s}%` } },
                ],
              })}
              displayLabel={(item) => [item.first_name, item.last_name].filter(Boolean).join(" ")}
              placeholder="Search and select merchant"
              initialValue={merchantId}
              onSelect={(item) => (merchantId = item?.id ?? "")}
            />
          </div>

          {#if isEditMode}
            <div class="space-y-2 md:col-span-2">
              <label for="product-status" class="text-sm font-medium text-foreground">Status</label>
              <button
                type="button"
                id="product-status"
                role="switch"
                aria-checked={isActive}
                onclick={() => (isActive = !isActive)}
                disabled={loading}
                class="flex items-center gap-3 disabled:opacity-50"
              >
                <span
                  class="relative inline-flex h-6 w-11 items-center rounded-full transition-colors {isActive ? 'bg-green-500' : 'bg-gray-300 dark:bg-gray-600'}"
                >
                  <span
                    class="inline-block h-4 w-4 transform rounded-full bg-white transition-transform {isActive ? 'translate-x-6' : 'translate-x-1'}"
                  ></span>
                </span>
                <span class="text-sm text-foreground">{isActive ? "Active" : "Inactive"}</span>
              </button>
            </div>
          {/if}

          <div class="space-y-2">
            <label for="product-type" class="text-sm font-medium text-foreground">
              Product Type <span class="text-destructive">*</span>
            </label>
            <select
              id="product-type"
              class="w-full px-3 py-2 border border-input rounded-md bg-background text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-info focus:ring-offset-1 disabled:opacity-50"
              value={productTypeId}
              onchange={handleProductTypeSelect}
              disabled={loading}
            >
              <option value="">Select product type</option>
              {#each productTypes as type}
                <option value={type.id}>{type.name}</option>
              {/each}
            </select>
          </div>

          <div class="space-y-2">
            <label for="default-unit" class="text-sm font-medium text-foreground">
              Default Unit <span class="text-destructive">*</span>
            </label>
            <select
              id="default-unit"
              class="w-full px-3 py-2 border border-input rounded-md bg-background text-sm text-foreground focus:outline-none focus:ring-2 focus:ring-info focus:ring-offset-1 disabled:opacity-50"
              bind:value={defaultUnit}
              disabled={loading}
            >
              <option value="">Select unit</option>
              {#each UNIT_OPTIONS as unit}
                <option value={unit}>{unit}</option>
              {/each}
            </select>
          </div>

          {#if !autoName}
            <div class="space-y-2 md:col-span-2">
              <label for="product-name" class="text-sm font-medium text-foreground">
                Name <span class="text-destructive">*</span>
              </label>
              <Input
                id="product-name"
                type="text"
                bind:value={productName}
                placeholder="Enter product name"
                class="w-full"
                disabled={loading}
              />
            </div>
          {/if}

          {#if selectedTypeKey === "brake_lining" || selectedTypeKey === "brake_pad" || selectedTypeKey === "break_pad"}
            <div class="space-y-2">
              <label for="model-no" class="text-sm font-medium text-foreground">
                Model No
              </label>
              <Input
                id="model-no"
                type="text"
                bind:value={modelNo}
                placeholder="e.g. 19932 / 00"
                class="w-full"
                disabled={loading}
              />
            </div>

            <div class="space-y-2">
              <label for="country" class="text-sm font-medium text-foreground">
                Country
              </label>
              <Input
                id="country"
                type="text"
                bind:value={country}
                placeholder="e.g. India"
                class="w-full"
                disabled={loading}
              />
            </div>
          {/if}

          {#if selectedTypeKey === "glass"}
            <div class="space-y-2">
              <label for="thickness" class="text-sm font-medium text-foreground">
                Thickness
              </label>
              <Input
                id="thickness"
                type="text"
                bind:value={thickness}
                placeholder="e.g. 4"
                class="w-full"
                disabled={loading}
              />
            </div>

            <div class="space-y-2">
              <label for="color" class="text-sm font-medium text-foreground">
                Color
              </label>
              <Input
                id="color"
                type="text"
                bind:value={color}
                placeholder="e.g. Bronze"
                class="w-full"
                disabled={loading}
              />
            </div>

            <div class="space-y-2">
              <label for="figure" class="text-sm font-medium text-foreground">
                Figure
              </label>
              <Input
                id="figure"
                type="text"
                bind:value={figure}
                placeholder="e.g. Neshija"
                class="w-full"
                disabled={loading}
              />
            </div>

            <div class="space-y-2">
              <label for="factor" class="text-sm font-medium text-foreground">
                Factor
              </label>
              <Input
                id="factor"
                type="text"
                bind:value={factor}
                placeholder="e.g. 3.2"
                class="w-full"
                disabled={loading}
              />
            </div>
          {/if}

          {#if autoName}
            <div class="space-y-2 md:col-span-2">
              <label for="generated-name" class="text-sm font-medium text-foreground">
                Product Name
              </label>
              <Input
                id="generated-name"
                type="text"
                value={displayName}
                placeholder="Fill in the attributes above — name is built automatically."
                class="w-full bg-muted/30"
                readonly
              />
              <p class="text-xs text-muted-foreground">
                Fill in the attributes above — name is built automatically.
              </p>
            </div>
          {/if}

          <div class="space-y-2">
            <label for="barcode" class="text-sm font-medium text-foreground">
              Barcode <span class="text-muted-foreground text-xs">(optional)</span>
            </label>
            <Input
              id="barcode"
              type="text"
              bind:value={barcode}
              placeholder="Enter barcode"
              class="w-full"
              disabled={loading}
            />
          </div>

          <div class="space-y-2">
            <label for="qr-code" class="text-sm font-medium text-foreground">
              QR Code <span class="text-muted-foreground text-xs">(optional)</span>
            </label>
            <Input
              id="qr-code"
              type="text"
              bind:value={qrCode}
              placeholder="Enter QR code"
              class="w-full"
              disabled={loading}
            />
          </div>

          <div class="space-y-2 md:col-span-2">
            <label for="threshold" class="text-sm font-medium text-foreground">
              Stock Threshold <span class="text-muted-foreground text-xs">(optional)</span>
            </label>
            <Input
              id="threshold"
              type="number"
              bind:value={threshold}
              placeholder="0"
              class="w-full"
              disabled={loading}
              min="0"
            />
          </div>
        </div>
        {/if}
      </div>

      <div class="flex items-center justify-end gap-3 p-6 border-t border-border">
        <Button
          variant="outline"
          onclick={handleClose}
          disabled={loading}
          class="border-border text-foreground hover:bg-muted"
        >
          Cancel
        </Button>
        <Button
          onclick={handleSubmit}
          disabled={loading}
          class="bg-[var(--primary-blue)] text-white hover:opacity-90 min-w-[140px]"
        >
          {#if loading}
            <svg class="animate-spin h-4 w-4 mr-2" viewBox="0 0 24 24">
              <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4" fill="none" />
              <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
            </svg>
          {/if}
          {isEditMode ? "Update Product" : "Create Product"}
        </Button>
      </div>
    </div>
  </div>
{/if}
