query getDashboardSalesTrend(
  $investorId: uuid!
  $year: Int
  $lastTwelveMonth: timestamptz!
  $ordersFilter: orders_bool_exp = {}
) {
  overall_orders: orders_aggregate(where: $ordersFilter) {
    aggregate {
      sum {
        total_amount
      }
    }
  }
  last_twelve_month: orders_aggregate(
    where: {
      _and: [{ created_at: { _gte: $lastTwelveMonth } }, $ordersFilter]
    }
  ) {
    aggregate {
      sum {
        total_amount
      }
    }
  }
  investor_sales_trend_global_report(
    args: { investor_id: $investorId, year: $year }
  ) {
    month
    total_sales
  }
}