query GetPaymentStats(
  $paymentFilter: payment_bool_exp!
  $ordersFilter: orders_bool_exp!
) {
  total_payment: payment_aggregate(where: $paymentFilter) {
    aggregate {
      sum {
        amount
      }
    }
  }
  total_payed: payment_aggregate(
    where: { _and: [{ order: { status: { _eq: "paid" } } }, $paymentFilter] }
  ) {
    aggregate {
      sum {
        amount
      }
    }
  }
  total_overdue: orders_aggregate(where: $ordersFilter) {
    aggregate {
      sum {
        outstanding_amount
      }
    }
  }
  completed_orderes: orders_aggregate(
    where: { _and: [{ status: { _eq: "paid" } }, $ordersFilter] }
  ) {
    aggregate {
      count
    }
  }
}